import type { Metadata } from "next";
import { Lexend, Mulish, Poppins } from "next/font/google";
import "./globals.css";
import NavbarPage from "@/src/components/NavbarPage";

const poppins = Lexend({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <NavbarPage />
        {children}
      </body>
    </html>
  );
}
